---
layout: default 
title: "817 - Your company is developing a nextgenerat"
---


[.question]
== 817-64a1df00aa736d27b1db92cb.


****

[.query]
--
Your company is developing a next-generation pet collar that collects biometric information to assist families with promoting healthy lifestyles for their pets.
Each collar will push 30kb of biometric data in JSON format every 2 seconds to a collection platform that will process and analyze the data providing health trending information back to the pet owners and veterinarians via a web portal.
Management has tasked you to architect the collection platform ensuring the following requirements are met.


--

[.list]
--
* [*] A. Utilize S3 to collect the inbound sensor data, analyze the data from S3 with a daily scheduled Data Pipeline and save the results to a Redshift Cluster.
* [*] B. Utilize Amazon Kinesis to collect the inbound sensor data, analyze the data with Kinesis Analytics and save the results to a Redshift cluster using EMR.
* [ ] C. Utilize S3 to collect the inbound sensor data analyze the data from SQS with Amazon Kinesis and save the results to a Microsoft SQL Server RDS instance.
* [ ] D. Utilize EMR to collect the inbound sensor data, analyze the data from EMR with Amazon Kinesis and save the results to DynamoD.

--
****

[.answer]
Answer  B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - B.
The main point to consider here is that the information is to be analyzed in real-time.
The solution should be highly durable, elastic, and processed in parallel.
The result should be persisted for data mining after the analysis.
Whenever the question requires real-time processing of data, always think about using Amazon Kinesis.
Option A is incorrect because (a) S3 is not efficient for collecting and storing real-time data, and (b) daily scheduled data pipeline is not a real-time analytics solution.
Option B is CORRECT because (a) Amazon Kinesis and Kinesis Analytics is ideal for capturing and processing real-time data respectively captured by the sensor, (b) it also stores the result of analysis later, and (c) Redshift cluster can be used for processing (data mining) the information captured by the Kinesis and copied via EMR.
Option C is incorrect because (a) S3 is not efficient for collecting and storing real-time data, and (b) MSSQL Server RDS is not ideal for storing the information for data mining.
Option D is incorrect because (a) EMR alone is not ideal for capturing data and would need specific frameworks like Kafka to capture data for processing.
Also, real-time analytics needs to be done using Spark Streaming and not EMR alone, and (b) DynamoDB is not used for data mining.
For more information on Amazon Kinesis with Redshift, go to this link-
https://docs.aws.amazon.com/firehose/latest/dev/what-is-this-service.html
The best answer for this scenario is B. Utilize Amazon Kinesis to collect the inbound sensor data, analyze the data with Kinesis Analytics, and save the results to a Redshift cluster using EMR.
Amazon Kinesis is a data streaming service that enables real-time processing of streaming data at scale. It is suitable for collecting and processing large amounts of data in real-time, such as the biometric data generated by the pet collars. With Kinesis, you can easily ingest, buffer, and process data in real-time.
Kinesis Analytics is a service that enables real-time analysis of streaming data using SQL queries. It allows you to analyze data as it is being generated and provides real-time insights into the data. Using Kinesis Analytics, you can easily process the JSON data generated by the pet collars and extract the relevant information.
EMR is a fully-managed Hadoop framework that makes it easy to process large amounts of data using distributed computing. EMR can be used in conjunction with Kinesis Analytics to save the results to a Redshift cluster. Redshift is a fully-managed data warehouse service that makes it easy to store and analyze large amounts of data. With Redshift, you can easily store and analyze the results generated by Kinesis Analytics.
Therefore, B is the best answer as it combines Kinesis and Kinesis Analytics for processing the incoming data, and then saves the results to Redshift using EMR for storage and analysis.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question22:"link"


