---
layout: default 
title: "806 - Serverside encryption is about data encr"
---


[.question]
== 806-64a1defdaa736d27b1db92bf.


****

[.query]
--
Server-side encryption is about data encryption at rest.
That is, Amazon S3 encrypts your data at the object level as it writes it to disk in its data centers and decrypts it for you when you go to access it.
A few different options are depending on how you choose to manage the encryption keys.
One of the options is called 'Server-Side Encryption with Amazon S3-Managed Keys (SSE-S3)'
Which of the following best describes how this encryption method works?


--

[.list]
--
* [*] A. There are separate permissions for the use of an envelope key (a key that protects your data`s encryption key) that provides added protection against unauthorized access of your objects in S3 and also provides you with an audit trail of when your key was used and by whom.
* [*] B. Each object is encrypted with a unique key employing strong encryption. As an additional safeguard, it encrypts the key itself with a master key that it regularly rotates.
* [ ] C. You manage the encryption keys and Amazon S3 manages the encryption, as it writes to disk, and decryption when you access your objects.
* [ ] D. A randomly generated data encryption key is returned from Amazon S3, which is used by the client to encrypt the object data.

--
****

[.answer]
Answer  B

[.explanation]
--
Click on the arrows to vote for the correct answer
A.
B.
C.
D.
Answer - B.
Server-side encryption with Amazon S3-managed encryption keys (SSE-S3) employs strong multi-factor encryption.
Amazon S3 encrypts each object with a unique key.
As an additional safeguard, it encrypts the key itself with a master key that it regularly rotates.
Amazon S3 server-side encryption uses one of the strongest block ciphers available, 256-bit Advanced Encryption Standard (AES-256), to encrypt your data.
Option A is incorrect because there are no separate permissions to the key that protects the data key.
Option B is CORRECT because as mentioned above, each object is encrypted with a strong unique key and that key itself is encrypted by a master key.
Option C is incorrect because the keys are managed by the AWS.
Option D is incorrect because there is no randomly generated key and the client does not do the encryption.
For more information on S3 encryption, please visit the links-
https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html
The Server-Side Encryption with Amazon S3-Managed Keys (SSE-S3) is a server-side encryption method that automatically encrypts the data you store in Amazon S3 at the object level. This means that S3 encrypts the data as it writes it to disk in its data centers, and decrypts it for you when you access it.
With SSE-S3, Amazon S3 manages the encryption keys, which provides a simple and cost-effective encryption solution. This method uses Advanced Encryption Standard (AES)-256, a secure symmetric-key encryption standard. SSE-S3 provides strong encryption of data at rest and helps to protect against unauthorized access to the data.
In SSE-S3, each object is encrypted with a unique key that is randomly generated by Amazon S3. As an additional safeguard, the encryption key itself is encrypted with a master key that is also managed by Amazon S3. Amazon S3 regularly rotates the master key to further enhance the security of the encrypted data.
The encryption keys are stored separately from the encrypted data, which adds an additional layer of security. When you access your objects, Amazon S3 decrypts the data using the appropriate encryption key. You do not need to manage the encryption keys, and you cannot access or retrieve them.
Therefore, Option B best describes how Server-Side Encryption with Amazon S3-Managed Keys (SSE-S3) works. It encrypts each object with a unique key employing strong encryption, and it encrypts the key itself with a master key that it regularly rotates. Amazon S3 manages the encryption keys, and you do not need to manage them.
--

[.ka]
null

'''



https://www.exam-answer.com/amazon/sap-c01/question9:"link"


